# 03-feb-2025-Range_&_Numpy

In [8]:
import numpy as np

In [12]:
np.__version__

'1.26.4'

# Create Array 

In [15]:
mlist = [1,2,3,4]

In [17]:
mlist

[1, 2, 3, 4]

In [19]:
type(mlist)

list

In [21]:
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

# WE convert list to array

In [24]:
arr = np.array(l)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [26]:
np.arange(25)  # We use arange function

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
np.arange(3.0) # arange([start,] stop[, step,], dtype=None, *, like=None)

array([0., 1., 2.])

In [36]:
np.arange(2,3) # arange([start,] stop[, step,], dtype=None, *, like=None)

array([2])

In [38]:
np.arange(2,30)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
np.arange(20,3)

array([], dtype=int32)

In [42]:
np.arange(-2,3)

array([-2, -1,  0,  1,  2])

In [44]:
np.arange(2,33)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [46]:
np.arange(2,30,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

# Zreo

In [51]:
np.zeros(3) #zeros(shape, dtype=float, order='C', *, like=None)

array([0., 0., 0.])

In [53]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [57]:
np.zeros((2,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
np.zeros((4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [61]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.zeros((2,10,3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [75]:
np.zeros((3,2,4), dtype=int) # 3 time, 2 rows, 4 column

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [77]:
np.zeros((2,3,3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

# One

In [82]:
np.ones((2,3,5), dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [84]:
# 2 time, 2 rows, 5 column

In [86]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [88]:
np.ones((2,4), dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

# Random

In [91]:
rand(3,2)
ranndom.rand(3,2)

NameError: name 'rand' is not defined

In [93]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [99]:
np.random.rand(3,2)

array([[0.32049602, 0.4949363 ],
       [0.87298407, 0.1836773 ],
       [0.06271068, 0.15361509]])

In [101]:
np.random.randint(3,2)

ValueError: low >= high

In [105]:
np.random.randint(3,12)

9

In [107]:
np.random.rand(3,2)

array([[0.34829981, 0.42083914],
       [0.06375023, 0.16135473],
       [0.11163644, 0.08895861]])

In [113]:
np.random.randint(-3,2)

-1

In [115]:
np.random.randint(-3,20,5)

array([-3, -3,  8, 15, 11])